language: node_js
node_js:
  - "8"
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - echo 'CI/CD'
        - echo 'Installing dependencies!'
        - yarn
        - echo 'Testing!'
        # Perform tests below;
        - npm test
